version: "3"
services:
  reverse-proxy:
    image: traefik:v2.4
    command:
      - "--api.insecure=true"
      - "--providers.docker"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.web.address=:80"
      - "--entryPoints.websecure.address=:443"
      - "--certificatesresolvers.myhttpchallenge.acme.httpchallenge=true"
      - "--certificatesresolvers.myhttpchallenge.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.myhttpchallenge.acme.email=jeffrey.vandevelde@hotmail.com"
      - "--certificatesresolvers.myhttpchallenge.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    depends_on:
      - back
      - front
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./letsencrypt:/letsencrypt

  front:
    image: thecodingmachine/nodejs:14
    environment:
      DEBUG_MODE: "$DEBUG_MODE"
      JITSI_URL: $JITSI_URL
      JITSI_PRIVATE_MODE: "$JITSI_PRIVATE_MODE"
      HOST: "0.0.0.0"
      NODE_ENV: development
      FRONT_URL: play.jeffreyvandevelde.be
      API_URL: pusher.jeffreyvandevelde.be
      UPLOADER_URL: uploader.jeffreyvandevelde.be
      ADMIN_URL: jeffreyvandevelde.be
      STARTUP_COMMAND_1: ./templater.sh
      STARTUP_COMMAND_2: yarn install
      TURN_SERVER: "turn:coturn.workadventu.re:443,turns:coturn.workadventu.re:443"
      TURN_USER: workadventure
      TURN_PASSWORD: WorkAdventure123
      START_ROOM_URL: "$START_ROOM_URL"
    command: yarn run start
    volumes:
      - ./front:/usr/src/app
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.front-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.front.middlewares=front-redirect"
      - "traefik.http.routers.front.rule=Host(`play.jeffreyvandevelde.be`)"
      - "traefik.http.routers.front.entryPoints=web,traefik"
      - "traefik.http.services.front.loadbalancer.server.port=8080"
      - "traefik.http.routers.front-ssl.rule=Host(`play.jeffreyvandevelde.be`)"
      - "traefik.http.routers.front-ssl.entryPoints=websecure"
      - "traefik.http.routers.front-ssl.tls.certresolver=myhttpchallenge"
      - "traefik.http.routers.front-ssl.tls=true"
      - "traefik.http.routers.front-ssl.service=front"
      - "traefik.http.middlewares.testheader.headers.accesscontrolalloworiginlist=https://play.jeffreyvandevelde.be,https://pusher.jeffreyvandevelde.be,https://api.jeffreyvandevelde.be,https://uploader.jeffreyvandevelde.be,https://maps.jeffreyvandevelde.be,https://play.jeffreyvandevelde.be:8080,https://pusher.jeffreyvandevelde.be:8080,https://api.jeffreyvandevelde.be:8080,https://uploader.jeffreyvandevelde.be:8080,https://maps.jeffreyvandevelde.be:8080"

  pusher:
    image: thecodingmachine/nodejs:12
    command: yarn dev
    #command: yarn run prod
    #command: yarn run profile
    environment:
      DEBUG: "*"
      STARTUP_COMMAND_1: yarn install
      SECRET_JITSI_KEY: "$SECRET_JITSI_KEY"
      SECRET_KEY: yourSecretKey
      ADMIN_API_TOKEN: "$ADMIN_API_TOKEN"
      API_URL: back:50051
      JITSI_URL: $JITSI_URL
      JITSI_ISS: $JITSI_ISS
    volumes:
      - ./pusher:/usr/src/app
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.pusher-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.pusher.middlewares=pusher-redirect"
      - "traefik.http.routers.pusher.rule=Host(`pusher.jeffreyvandevelde.be`)"
      - "traefik.http.routers.pusher.entryPoints=web"
      - "traefik.http.services.pusher.loadbalancer.server.port=8080"
      - "traefik.http.routers.pusher-ssl.rule=Host(`pusher.jeffreyvandevelde.be`)"
      - "traefik.http.routers.pusher-ssl.entryPoints=websecure"
      - "traefik.http.routers.pusher-ssl.tls.certresolver=myhttpchallenge"
      - "traefik.http.routers.pusher-ssl.tls=true"
      - "traefik.http.routers.pusher-ssl.service=pusher"
      - "traefik.http.middlewares.testheader.headers.accesscontrolalloworiginlist=https://play.jeffreyvandevelde.be,https://pusher.jeffreyvandevelde.be,https://api.jeffreyvandevelde.be,https://uploader.jeffreyvandevelde.be,https://maps.jeffreyvandevelde.be,https://play.jeffreyvandevelde.be:8080,https://pusher.jeffreyvandevelde.be:8080,https://api.jeffreyvandevelde.be:8080,https://uploader.jeffreyvandevelde.be:8080,https://maps.jeffreyvandevelde.be:8080"

  maps:
    image: thecodingmachine/nodejs:12-apache
    environment:
      DEBUG_MODE: "$DEBUG_MODE"
      HOST: "0.0.0.0"
      NODE_ENV: development
      #APACHE_DOCUMENT_ROOT: dist/
      #APACHE_EXTENSIONS: headers
      #APACHE_EXTENSION_HEADERS: 1
      STARTUP_COMMAND_0: sudo a2enmod headers
      STARTUP_COMMAND_1: yarn install
      STARTUP_COMMAND_2: yarn run dev &
    volumes:
      - ./maps:/var/www/html
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.maps-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.maps.middlewares=maps-redirect"
      - "traefik.http.routers.maps.rule=Host(`maps.jeffreyvandevelde.be`)"
      - "traefik.http.routers.maps.entryPoints=web,traefik"
      - "traefik.http.services.maps.loadbalancer.server.port=80"
      - "traefik.http.routers.maps-ssl.rule=Host(`maps.jeffreyvandevelde.be`)"
      - "traefik.http.routers.maps-ssl.entryPoints=websecure"
      - "traefik.http.routers.maps-ssl.tls.certresolver=myhttpchallenge"
      - "traefik.http.routers.maps-ssl.tls=true"
      - "traefik.http.routers.maps-ssl.service=maps"
      - "traefik.http.middlewares.testheader.headers.accesscontrolalloworiginlist=https://play.jeffreyvandevelde.be,https://pusher.jeffreyvandevelde.be,https://api.jeffreyvandevelde.be,https://uploader.jeffreyvandevelde.be,https://maps.jeffreyvandevelde.be,https://play.jeffreyvandevelde.be:8080,https://pusher.jeffreyvandevelde.be:8080,https://api.jeffreyvandevelde.be:8080,https://uploader.jeffreyvandevelde.be:8080,https://maps.jeffreyvandevelde.be:8080"

  back:
    image: thecodingmachine/nodejs:12
    command: yarn dev
    #command: yarn run profile
    environment:
      DEBUG: "*"
      STARTUP_COMMAND_1: yarn install
      SECRET_KEY: yourSecretKey
      SECRET_JITSI_KEY: "$SECRET_JITSI_KEY"
      ALLOW_ARTILLERY: "true"
      ADMIN_API_TOKEN: "$ADMIN_API_TOKEN"
      JITSI_URL: $JITSI_URL
      JITSI_ISS: $JITSI_ISS
    volumes:
      - ./back:/usr/src/app
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.back-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.back.middlewares=back-redirect"
      - "traefik.http.routers.back.rule=Host(`api.jeffreyvandevelde.be`)"
      - "traefik.http.routers.back.entryPoints=web"
      - "traefik.http.services.back.loadbalancer.server.port=8080"
      - "traefik.http.routers.back-ssl.rule=Host(`api.jeffreyvandevelde.be`)"
      - "traefik.http.routers.back-ssl.entryPoints=websecure"
      - "traefik.http.routers.back-ssl.tls.certresolver=myhttpchallenge"
      - "traefik.http.routers.back-ssl.tls=true"
      - "traefik.http.routers.back-ssl.service=back"
      - "traefik.http.middlewares.testheader.headers.accesscontrolalloworiginlist=https://play.jeffreyvandevelde.be,https://pusher.jeffreyvandevelde.be,https://api.jeffreyvandevelde.be,https://uploader.jeffreyvandevelde.be,https://maps.jeffreyvandevelde.be,https://play.jeffreyvandevelde.be:8080,https://pusher.jeffreyvandevelde.be:8080,https://api.jeffreyvandevelde.be:8080,https://uploader.jeffreyvandevelde.be:8080,https://maps.jeffreyvandevelde.be:8080"

  uploader:
    image: thecodingmachine/nodejs:12
    command: yarn dev
    #command: yarn run profile
    environment:
      DEBUG: "*"
      STARTUP_COMMAND_1: yarn install
    volumes:
      - ./uploader:/usr/src/app
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.uploader-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.uploader.middlewares=uploader-redirect"
      - "traefik.http.routers.uploader.rule=Host(`uploader.jeffreyvandevelde.be`)"
      - "traefik.http.routers.uploader.entryPoints=web"
      - "traefik.http.services.uploader.loadbalancer.server.port=8080"
      - "traefik.http.routers.uploader-ssl.rule=Host(`uploader.jeffreyvandevelde.be`)"
      - "traefik.http.routers.uploader-ssl.entryPoints=websecure"
      - "traefik.http.routers.uploader-ssl.tls.certresolver=myhttpchallenge"
      - "traefik.http.routers.uploader-ssl.tls=true"
      - "traefik.http.routers.uploader-ssl.service=uploader"
      - "traefik.http.middlewares.testheader.headers.accesscontrolalloworiginlist=https://play.jeffreyvandevelde.be,https://pusher.jeffreyvandevelde.be,https://api.jeffreyvandevelde.be,https://uploader.jeffreyvandevelde.be,https://maps.jeffreyvandevelde.be,https://play.jeffreyvandevelde.be:8080,https://pusher.jeffreyvandevelde.be:8080,https://api.jeffreyvandevelde.be:8080,https://uploader.jeffreyvandevelde.be:8080,https://maps.jeffreyvandevelde.be:8080"

  messages:
    #image: thecodingmachine/nodejs:14
    image: thecodingmachine/workadventure-back-base:latest
    environment:
      #STARTUP_COMMAND_0: sudo apt-get install -y inotify-tools
      STARTUP_COMMAND_1: yarn install
      STARTUP_COMMAND_2: yarn run proto:watch
    volumes:
      - ./messages:/usr/src/app
      - ./back:/usr/src/back
      - ./front:/usr/src/front
      - ./pusher:/usr/src/pusher

